# Generated by Django 3.2.3 on 2023-01-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Robots',
        ),
    ]
