# Generated by Django 3.2.3 on 2023-01-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiting_list',
            field=models.BooleanField(default=False),
        ),
    ]
